workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      sdk: "android-33"
      java: 17
    scripts:
      - name: Build APK
        script: |
          ./gradlew clean assembleProductionRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-keithantodc@gmail.com
